# Site settings
title: Camp Kesem at the Claremont Colleges Newsletter
header-img: img/home-bg2.jpg
email: claremont@campkesem.org
copyright_name: Camp Kesem at the Claremont Colleges
description: "Camp Kesem at the Claremont Colleges' monthly newsletter. We're a nonprofit that provides a camp for children who's parents are affected by cancer."
baseurl: ""
url: "http://campkesemclaremont.us"
twitter_username: campkesemclaremont
instagram_username:  campkesemclaremont
facebook_username:  campkesemclaremont
email_username:  claremont@campkesem.org

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
